server:
  port: 8060

custom:

  pfxPath: /usr/local/tomcat/project/wosign-contract/data/pfx/pfx.pfx
  picPath: /usr/local/tomcat/project/wosign-contract/data/pic/
  pdfPath: /usr/local/tomcat/project/wosign-contract/data/pdf/
  tokenid: 184b28d9-1979-447b-9626-e45fc2389624
